import { SellerProduct, SellerOrder, SellerStats } from "@/types/seller";

export const mockSellerProducts: SellerProduct[] = [
  {
    id: "1",
    name: "Premium Leather Messenger Bag",
    description: "Handcrafted genuine leather messenger bag perfect for professionals. Features multiple compartments, adjustable strap, and durable brass hardware.",
    price: 120,
    images: ["/products/leather-bag-1.jpg"],
    category: "Leather Bags",
    inStock: true,
    stockQuantity: 25,
    minimumOrder: 1,
    deliveryTime: "14-21 days",
    tags: ["Leather", "Bags", "Professional", "Handmade"],
    status: "active",
    createdAt: new Date("2024-10-15"),
    updatedAt: new Date("2025-01-20"),
    specifications: {
      Material: "Genuine Leather",
      Dimensions: "15\" x 11\" x 4\"",
      Color: "Brown, Black",
      Weight: "2.5 lbs",
    },
  },
  {
    id: "2",
    name: "Custom Leather Wallet",
    description: "Slim leather wallet with RFID protection. Can be customized with initials or logo.",
    price: 35,
    images: ["/products/wallet-1.jpg"],
    category: "Accessories",
    inStock: true,
    stockQuantity: 150,
    minimumOrder: 5,
    deliveryTime: "7-14 days",
    tags: ["Leather", "Wallet", "Custom", "RFID"],
    status: "active",
    createdAt: new Date("2024-11-01"),
    updatedAt: new Date("2025-01-22"),
    specifications: {
      Material: "Full-grain Leather",
      Dimensions: "4.5\" x 3.5\"",
      Features: "RFID Protection",
    },
  },
  {
    id: "3",
    name: "Leather Belt with Custom Buckle",
    description: "Handcrafted leather belt with custom brass buckle. Available in multiple colors.",
    price: 32,
    images: ["/products/belt-1.jpg"],
    category: "Accessories",
    inStock: false,
    stockQuantity: 0,
    minimumOrder: 5,
    deliveryTime: "7-14 days",
    tags: ["Belt", "Leather", "Custom", "Accessories"],
    status: "out_of_stock",
    createdAt: new Date("2024-09-20"),
    updatedAt: new Date("2025-01-10"),
    specifications: {
      Material: "Full-grain Leather",
      Width: "1.5 inches",
      Buckle: "Solid brass",
    },
  },
  {
    id: "4",
    name: "Executive Leather Briefcase",
    description: "Professional briefcase for business executives. Premium quality with lifetime guarantee.",
    price: 250,
    images: ["/products/briefcase-1.jpg"],
    category: "Leather Bags",
    inStock: true,
    stockQuantity: 8,
    minimumOrder: 1,
    deliveryTime: "21-30 days",
    tags: ["Briefcase", "Executive", "Professional", "Premium"],
    status: "active",
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date("2025-01-23"),
    specifications: {
      Material: "Premium Italian Leather",
      Dimensions: "17\" x 13\" x 5\"",
      Features: "Laptop compartment, Lock system",
    },
  },
  {
    id: "draft-1",
    name: "New Leather Backpack Design",
    description: "Work in progress - stylish leather backpack for daily use.",
    price: 95,
    images: [],
    category: "Leather Bags",
    inStock: false,
    stockQuantity: 0,
    minimumOrder: 1,
    deliveryTime: "14-21 days",
    tags: ["Backpack", "Leather", "Casual"],
    status: "draft",
    createdAt: new Date("2025-01-24"),
    updatedAt: new Date("2025-01-24"),
  },
];

export const mockSellerOrders: SellerOrder[] = [
  {
    id: "ORD-1234567890",
    buyerName: "John Smith",
    buyerEmail: "john.smith@email.com",
    items: [
      {
        productId: "1",
        productName: "Premium Leather Messenger Bag",
        quantity: 1,
        price: 120,
        includeInspect: true,
      },
      {
        productId: "2",
        productName: "Custom Leather Wallet",
        quantity: 5,
        price: 35,
        includeInspect: false,
      },
    ],
    subtotal: 295,
    status: "preparing",
    shippingAddress: {
      fullName: "John Smith",
      address: "4567 Main Street, Apt 2B",
      city: "Houston",
      state: "TX",
      zipCode: "77002",
      country: "USA",
    },
    createdAt: new Date("2025-01-15"),
    estimatedDelivery: "Feb 10-15, 2025",
  },
  {
    id: "ORD-1234567895",
    buyerName: "Sarah Johnson",
    buyerEmail: "sarah.j@email.com",
    items: [
      {
        productId: "4",
        productName: "Executive Leather Briefcase",
        quantity: 2,
        price: 250,
        includeInspect: true,
      },
    ],
    subtotal: 500,
    status: "inspection_requested",
    shippingAddress: {
      fullName: "Sarah Johnson",
      address: "789 Oak Avenue",
      city: "Houston",
      state: "TX",
      zipCode: "77005",
      country: "USA",
    },
    createdAt: new Date("2025-01-22"),
    estimatedDelivery: "Feb 20-25, 2025",
  },
  {
    id: "ORD-1234567896",
    buyerName: "Michael Brown",
    buyerEmail: "mbrown@email.com",
    items: [
      {
        productId: "2",
        productName: "Custom Leather Wallet",
        quantity: 10,
        price: 35,
        includeInspect: false,
      },
    ],
    subtotal: 350,
    status: "pending",
    shippingAddress: {
      fullName: "Michael Brown",
      address: "321 Pine Street",
      city: "Houston",
      state: "TX",
      zipCode: "77008",
      country: "USA",
    },
    createdAt: new Date("2025-01-25"),
    estimatedDelivery: "Feb 15-20, 2025",
  },
  {
    id: "ORD-1234567897",
    buyerName: "Emily Davis",
    buyerEmail: "emily.d@email.com",
    items: [
      {
        productId: "1",
        productName: "Premium Leather Messenger Bag",
        quantity: 3,
        price: 120,
        includeInspect: true,
      },
    ],
    subtotal: 360,
    status: "ready_to_ship",
    shippingAddress: {
      fullName: "Emily Davis",
      address: "456 Elm Drive",
      city: "Houston",
      state: "TX",
      zipCode: "77010",
      country: "USA",
    },
    createdAt: new Date("2025-01-18"),
    estimatedDelivery: "Feb 12-17, 2025",
  },
];

export const mockSellerStats: SellerStats = {
  totalProducts: 5,
  activeProducts: 3,
  totalOrders: 523,
  pendingOrders: 4,
  completedOrders: 519,
  totalRevenue: 62760,
  thisMonthRevenue: 4250,
  averageRating: 4.9,
  totalReviews: 487,
};

export const getSellerOrderStatusLabel = (status: string): string => {
  const labels: Record<string, string> = {
    pending: "New Order",
    preparing: "Preparing",
    inspection_requested: "Inspection Requested",
    ready_to_ship: "Ready to Ship",
    shipped: "Shipped",
    delivered: "Delivered",
    completed: "Completed",
    cancelled: "Cancelled",
  };
  return labels[status] || status;
};

export const getSellerOrderStatusColor = (status: string): string => {
  const colors: Record<string, string> = {
    pending: "bg-blue-100 text-blue-700",
    preparing: "bg-yellow-100 text-yellow-700",
    inspection_requested: "bg-purple-100 text-purple-700",
    ready_to_ship: "bg-green-100 text-green-700",
    shipped: "bg-orange-100 text-orange-700",
    delivered: "bg-green-100 text-green-700",
    completed: "bg-gray-100 text-gray-700",
    cancelled: "bg-red-100 text-red-700",
  };
  return colors[status] || "bg-gray-100 text-gray-700";
};
